### ISSUE TITLE
Wikidata Search

### ISSUE THREAD

**Issue by ozgurakyazi** [bounswe/bounswe2016group11#100]
We should be able to search a term(keyword) in wikidata. After having this functionality, we will integrate this into search bar(it will be so basic) and possibly into tagging(especially in create topic page ) part.

**Comment by ktekelioglu** [comment]
It is possible to call the Wikidata Search through its API, which returns a set of results in JSON Format. For example, we can use this query to search for Donald Trump:

https://www.wikidata.org/w/api.php?action=wbsearchentities&search=Donald%20Trump&language=en&format=json

So, Im guessing that we want the search parameter to be passed as an argument to a POST request, and you'll be parsing the json to generate a list of results in the front-end.

We can discuss this in today's meeting.

**Comment by ktekelioglu** [comment]
Added backend for a simple search. You can call /wikidataSearch/<Search String>/ to get results in JSON format.
