### ISSUE TITLE
Recommendations on Global Page

### ISSUE THREAD

**Issue by ozgurakyazi** [bounswe/bounswe2016group11#128]
Front end expects a javascript object which includes the recommended topics and posts in global page. Please write a program which returns a recommended topics and posts(which is specific to user, if user is not logged in then return populars). It is better for us to do that as API, web and android could utilize it easily.

Please check #127 .

**Comment by dogukan1905** [comment]
https://github.com/bounswe/bounswe2016group11/pull/149

**Comment by ozgurakyazi** [comment]
will be decided on 8 December 13:00

**Comment by ktekelioglu** [comment]
Recommendation is added to topics. It is based on how many times and at last when the neighbor topics are visited.
