### ISSUE TITLE
Topics' grade in Global page

### ISSUE THREAD

**Issue by ozgurakyazi** [bounswe/bounswe2016group11#133]
from 0 to 100 scale, for each topic, a number which shows the popularity or hotness of a topic should be returned in global page. Front end will calibrate a color according to that color.

**Comment by ozgurakyazi** [comment]
will be decided on 8 December 13:00

**Comment by ktekelioglu** [comment]
Added hotness as a property to Topics. The formula is (# of posts) - 2* (hours_since_last_post) - (hours_since_topic_creation). /getHotTopics/x/ returns the hottest x Topics.
