### ISSUE TITLE
Post Edit-Delete 

### ISSUE THREAD

**Issue by ozgurakyazi** [bounswe/bounswe2016group11#167]
Two endpoints should be implemented one for editing the post and the other is for deleting. Please see the associated issue #166 . The incoming information for editing the post:
  -id of the post, 
  -new text to replace the old one,
  -new set of tags
For the delete post associated information is:
 - id of the post.

Also, the user of the editor should be the same with the creator of the post.

**Comment by dogukan1905** [comment]
https://github.com/bounswe/bounswe2016group11/pull/169

data structures are shown in the pull request.
