### ISSUE TITLE
Acceptance Criterias

### ISSUE THREAD

**Issue by mmervecerit** [bounswe/bounswe2016group11#5]

**Comment by ozgurakyazi** [comment]
Bunu açtığın çok iyi olmuş... Burayı daha çok kullanabiliriz bence.

**Comment by mmervecerit** [comment]
Aynen ya çok işe yarıyor bence de

**Comment by mbarsbey** [comment]
Bunu kapattım arkadaşlar. Şu anda acceptance criteria eksiğimiz yok.
