### ISSUE TITLE
Revising Mock-ups

### ISSUE THREAD

**Issue by mmervecerit** [bounswe/bounswe2016group11#58]

**Comment by dcelik** [comment]
@team

**Comment by mbarsbey** [comment]
Mockup revisions shall include creation of a more narrative based / real data content, as well as inclusion of newly agreed upon functionalities with the customers.

**Comment by mbarsbey** [comment]
Mockup scenarios have been created for searching for a topic, navigating between topics, posting under a topic, adding relationships, using advanced search to view a user page, and creating a topic.
