### ISSUE TITLE
SQL Dump

### ISSUE THREAD

**Issue by ktekelioglu** [bounswe/bounswe2016group11#95]
Learn how to get SQL dump from PSQL to dump to MySQL.

**Comment by ozgurakyazi** [comment]
I assume that the link (https://www.postgresql.org/docs/9.1/static/backup-dump.html ) from postgres will be so helpful. Also this tool looked so convincing to me (http://www.lightbox.ca/pg2mysql.php).

Are those enough to close this issue ? :)

**Comment by ozgurakyazi** [comment]
This will be opened later...

For now, we do not need the dump
