### ISSUE TITLE
Login/Signup should be functional(WEB)...

### ISSUE THREAD

**Issue by ozgurakyazi** [bounswe/bounswe2016group11#97]
This relates to both backend and frontend. I am assigning 1 person from each, please change the assignees as you wish.

**Comment by ozgurakyazi** [comment]
After #114  this will be closed. Now I am working on UI part of the authentication.

**Comment by ozgurakyazi** [comment]
@dogukan1905 @ozdemir08  I need help in this issue, how can I customize the allauth signup loging pages ?

**Comment by dogukan1905** [comment]
Backend is done. Frontend team has been informed about how to customize templates.
https://github.com/bounswe/bounswe2016group11/pull/142

**Comment by ozgurakyazi** [comment]
After doğukan's updates, frontend beautified pages. Now we have these features
