### ISSUE TITLE
Global Page JSON to render

### ISSUE THREAD

**Issue by ozgurakyazi** [bounswe/bounswe2016group11#98]
Because we will be rendering the data in the global page, we assumed we have a json file which includes the info about topics and their relations. When requesting the link /cocomapapp, please provide us with such a json file, you can find an example of it in cocomapapp/static/globalPageInfo.json

**Comment by dogukan1905** [comment]
https://github.com/bounswe/bounswe2016group11/pull/101

**Comment by dogukan1905** [comment]
siz kontrol ettikten sonra issue kapatılabilir

**Comment by ozgurakyazi** [comment]
Bikac saat icinde kontrol etmis olurum...

**Comment by ozgurakyazi** [comment]
For the current data, I wrote the frontend to render with it. However, for related topics, we need some enhancements.   For  "relates_to" field,  the value should always be a json arrray which includes both id and relation names for that relation.

**Comment by ozgurakyazi** [comment]
This is ok for now, there will be enhancements :+1:
