### ISSUE TITLE
Topic View JSON to Render

### ISSUE THREAD

**Issue by ozgurakyazi** [bounswe/bounswe2016group11#99]
As in #98 , we assumed a json to render the page. An example of the json file could be found in /cocomapapp/static/topic.json. Please provide us with such file, if there are any inconveniences, you are free to correct our assumption.

Thank you :)

**Comment by dogukan1905** [comment]
https://github.com/bounswe/bounswe2016group11/pull/101

**Comment by dogukan1905** [comment]
siz kontrol ettikten sonra issue kapatılabilir
